# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gioele Bencivenga
subtitle: Programming and stuff
title-separator: "-" # no clue what this does
email:
name: "Gioele Bencivenga"
description: >- # this means to ignore newlines until "baseurl:"
  Just another website.
logo: /assets/images/logo.png
# can be overridden at anytime by applying the following to a document’s YAML Front Matter
# header:
#   teaser: /assets/images/my-awesome-post-teaser.jpg
teaser: /assets/images/default-teaser.jpg # fallback teaser image in related posts
twitter_username: "sgnerpock45due"
github_username: Gioele-Bencivenga
minimal_mistakes_skin: dark
search: true
words_per_minute: 250 # reading speed used to calculate minutes to read article

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones, if not set the OS timezone is used

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Gioele Bencivenga"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "I like programming sometimes."
  links:
    - label: "GitHub"
      icon: "fab fa-github-square"
      url: "https://github.com/Gioele-Bencivenga"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sgnerpock45due"
    - label: "Itch"
      icon: "fab fa-itch-io"
      url: "https://gioele-bencivenga.itch.io/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github-square"
      url: "https://github.com/Gioele-Bencivenga"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sgnerpock45due"
    - label: "Itch"
      icon: "fab fa-itch-io"
      url: "https://gioele-bencivenga.itch.io/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _games
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      share: true

# These settings essentially say output index.html files for each games document in the _games folder
collections:
  games:
    output: true
    permalink: /:collection/:path/

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development # disable compression in dev environment
